### PR TITLE
Send event when new activites are added via auto update. I do not use…

### PR DESCRIPTION
**Pull request by hugifix**
… observer because I think the eventy should not happen for lazy loading if user scrolls.

### CODE REVIEW

**Comment by istvank** [comment]
What kind of event!?

**Comment by istvank** [comment]
The event name is not really according to best practice. It is "_newActivitiesViaAutoUpdate" but it should be something like "new-activities-loaded". I don't think we need the "ViaAutoUpdate" there.

**Comment by istvank** [comment]
The method name "_newActivitiesViaAutoUpdate" does not really tell you what the method does. "_fireNewActivitiesLoadedEvent" or something.

I think it should be "newly loaded activities" in the documentation.

**Comment by istvank** [comment]
And lastly :) Events can be annotated:
https://www.polymer-project.org/2.0/docs/tools/documentation#events

**Comment by hugifix** [comment]
Please check for merge

**Review by istvank — CHANGES_REQUESTED** [review]
In the ReqBaz frontend code, we do two things for event handlers: a) start with "_handle" (which is an indicator that it is an event) and b) end with the activity action. Therefore the "_handleClickActivityEvent" would be "_handleActivityTap". Which is even shorter. :) But it's not that big of a deal.

The other thing is that the "_handleNewActivitiesLoadedEvent" is not really an event listener that is bound to something (or is it?). It can have a name which makes it clearer what happens: "_fireNewActivitiesEvent" or something.

Lastly, do we really want to send all new activities around? What about just the plain number to display them in the badge?

**Review by istvank — APPROVED** [review]

**Pull request merged**
