### PR TITLE
Update readme index

### PR DESCRIPTION
**Pull request by hugifix**
~~Please do not merge pull request.~~
I think also about making activities private, but I am not sure. What do you think?

### CODE REVIEW

**Comment by istvank** [comment]
Why not merging this pull request?
Where do you want to make them private?

**Comment by hugifix** [comment]
I am not sure if activities should be visible from the outside.
We could also making activities only read only, so that they can not be manipulated.
Just an idea. If you think the actual state is fine you can merge.

**Comment by hugifix** [comment]
We could use "readOnly: true" for activities so that the frontend can read but not manipulate them.

**Comment by hugifix** [comment]
Ready for merge.

**Pull request merged**
